import Foundation

/// The sandbox desktop behind the `computer` tool: an XFCE session on X11
/// inside the Agent Sandbox guest, drawn on a virtio-gpu scanout the app shows
/// live (`DesktopPane`). Nothing here talks to a VM — these are the generated
/// guest-side scripts and the pure decisions around them, so every contract is
/// unit-testable. `AgentSandbox.ensureDesktopProvisioned` runs them.
///
/// Provisioning is `apt-get` on first enable into the WRITABLE rootfs dir
/// (`~/.mlx-serve/sandbox/images/…`), which persists across boots and is wiped
/// by a base-image re-pull — the version marker lives there too, so a re-pull
/// re-installs by construction and a bumped `provisionVersion` re-installs on
/// the next enable. Anything the model later installs with apt lives the same
/// way.
enum SandboxDesktop {

    /// Bump when `packages` or the scripts change in a way an existing rootfs
    /// must pick up. The marker carries it.
    static let provisionVersion = 2
    static let markerPath = "/var/lib/mlx-desktop/provisioned"
    /// Exit code of the last install, written LAST by the provision script.
    /// Its presence is "the install finished", its content is how.
    static let doneFilePath = "/var/lib/mlx-desktop/done"
    static let installLogPath = "/var/log/mlx-desktop-install.log"
    static let desktopLogPath = "/var/log/mlx-desktop.log"
    /// Where the host writes the provision script (rootfs dir, host side —
    /// virtiofs makes it appear in the live guest at once).
    static let provisionGuestPath = "/.vz-desktop-provision"
    static let alreadyProvisionedLine = "mlx-desktop: already provisioned"
    static let doneMarker = "MLX_DESKTOP_DONE="
    /// What `mlx-computer` and the tool prompt call the screen.
    static let display = VzGuest.DisplaySpec()

    /// `--no-install-recommends`: the X server (the modesetting driver for the
    /// virtio-gpu DRM node ships in -core; fbdev is the fallback on /dev/fb0),
    /// explicit input drivers (no udev in the guest, see `startScript`), a
    /// minimal XFCE, and what `mlx-computer` shells out to. ~350 MB.
    static let packages: [String] = [
        "xserver-xorg-core", "xserver-xorg-input-libinput", "xserver-xorg-input-evdev",
        "xserver-xorg-video-fbdev", "xinit", "x11-xserver-utils", "dbus-x11",
        "xfce4-session", "xfce4-panel", "xfwm4", "xfdesktop4", "xfce4-terminal", "thunar",
        "xdotool", "xclip", "scrot", "at-spi2-core", "python3-pyatspi", "python3-gi", "python3-pil",
        "fonts-dejavu-core",
        // A browser is what "use the computer" mostly means; `navigate` drives
        // it. ESR from Debian, policies below keep it quiet and predictable.
        "firefox-esr",
    ]

    /// Firefox enterprise policies (Debian reads `/etc/firefox-esr/policies/`):
    /// no crash-restore interstitial after a guest reboot (a 3B model opened
    /// "Restore Session" and never got past it), no first-run pages, no
    /// update or telemetry chatter, DuckDuckGo HTML as the search engine.
    static let firefoxPolicies = """
    {"policies": {"DisableSessionRestore": true, "OverrideFirstRunPage": "", "OverridePostUpdatePage": "",
                  "DisableAppUpdate": true, "DisableTelemetry": true, "NoDefaultBookmarks": true,
                  "DontCheckDefaultBrowser": true, "DisableFirefoxStudies": true,
                  "Homepage": {"URL": "about:blank", "StartPage": "none"},
                  "UserMessaging": {"ExtensionRecommendations": false, "FeatureRecommendations": false,
                                    "SkipOnboarding": true, "MoreFromMozilla": false},
                  "Preferences": {"browser.sessionstore.resume_from_crash": {"Value": false, "Status": "locked"},
                                  "accessibility.force_disabled": {"Value": 0, "Status": "locked"}}}}
    """

    /// Idempotent installer. Runs INSIDE the guest, backgrounded by the host
    /// (there is no streaming exec), logging to `installLogPath`; the host
    /// polls `pollCommand` until the done file appears.
    static var provisionScript: String {
        """
        #!/bin/sh
        # generated by mlx-serve (SandboxDesktop.provisionScript)
        MARK=\(markerPath)
        mkdir -p /var/lib/mlx-desktop /var/log
        if [ "$(cat "$MARK" 2>/dev/null)" = "provisioned=\(provisionVersion)" ]; then
          echo "\(alreadyProvisionedLine)"
          exit 0
        fi
        rm -f \(doneFilePath)
        export DEBIAN_FRONTEND=noninteractive
        mkdir -p /etc/firefox-esr/policies
        cat > /etc/firefox-esr/policies/policies.json <<'POLICIES'
        \(firefoxPolicies)
        POLICIES
        apt-get update && apt-get install -y --no-install-recommends \(packages.joined(separator: " "))
        rc=$?
        if [ "$rc" -eq 0 ]; then
          echo "provisioned=\(provisionVersion)" > \(markerPath)
          echo "mlx-desktop: provisioned (version \(provisionVersion))"
        else
          echo "mlx-desktop: apt-get failed with exit code $rc"
        fi
        echo "$rc" > \(doneFilePath)
        exit "$rc"

        """
    }

    /// The `/.vz-desktop-start` launcher: the boot-time arm (run by /.vz-init
    /// when /dev/dri/card0 exists) and the after-provision arm (run in place on
    /// a live guest). Safe on an unprovisioned rootfs (exit 0 with one line)
    /// and against a live display (no second X).
    ///
    /// No udev in the guest, so Xorg cannot discover input devices: the script
    /// writes explicit InputDevice sections for every /dev/input/event* (VZ's
    /// USB keyboard + absolute pointer, enumerated by the kernel's own xHCI +
    /// usbhid) with hotplug OFF, on the evdev driver (libinput's path backend
    /// still asks udev about the node and declines it, live 2026-09-05). An explicit ServerLayout must also name a
    /// Screen, or Xorg drops the auto-probed one ("Screen 0 deleted because of
    /// no matching config section", live 2026-09-05): the modesetting Device
    /// on the virtio-gpu DRM node is spelled out too. Xorg runs as root, like everything else in
    /// this throwaway guest. X never listens on TCP.
    static var startScript: String {
        """
        #!/bin/sh
        # generated by mlx-serve (SandboxDesktop.startScript)
        export DISPLAY=:0 HOME=/root XDG_RUNTIME_DIR=/run/user/0
        export GTK_MODULES=gail:atk-bridge GNOME_ACCESSIBILITY=1 QT_ACCESSIBILITY=1 NO_AT_BRIDGE=0
        if ! command -v Xorg >/dev/null 2>&1 || ! command -v xinit >/dev/null 2>&1; then
          echo "mlx-desktop: Xorg not installed yet (provision first)"
          exit 0
        fi
        if pidof Xorg >/dev/null 2>&1; then
          echo "mlx-desktop: display :0 already up"
          exit 0
        fi
        # The rootfs /tmp persists across boots: a lock from the previous boot
        # would make Xorg refuse ("Server is already active for display 0").
        rm -f /tmp/.X0-lock /tmp/.X11-unix/X0
        mkdir -p /run/user/0 /run/dbus /tmp/.X11-unix /etc/X11/xorg.conf.d /var/log
        # USB HID enumerates a moment after init runs us, keyboard BEFORE the
        # pointer: wait for the digitizer (VZ's absolute pointing device),
        # or the config below is written without it and the Mac's mouse
        # never reaches X (live 2026-09-06: keyboard worked, clicks did not).
        # event0 is the platform gpio-keys node.
        i=0
        while ! grep -q Digitizer /proc/bus/input/devices 2>/dev/null && [ $i -lt 40 ]; do sleep 0.25; i=$((i+1)); done
        chmod 700 /run/user/0; chmod 1777 /tmp/.X11-unix
        [ -e /run/dbus/pid ] || dbus-daemon --system --fork 2>/dev/null || true
        {
          echo 'Section "ServerFlags"'
          echo '  Option "AutoAddDevices" "off"'
          echo '  Option "AutoEnableDevices" "off"'
          echo '  Option "DontVTSwitch" "on"'
          echo 'EndSection'
          echo 'Section "Device"'
          echo '  Identifier "gpu"'
          echo '  Driver "modesetting"'
          echo '  Option "kmsdev" "/dev/dri/card0"'
          # The hardware cursor plane is not composited into VZ's scanout:
          # the pointer was invisible over the pane. Draw it in software.
          echo '  Option "SWcursor" "on"'
          echo 'EndSection'
          echo 'Section "Screen"'
          echo '  Identifier "screen"'
          echo '  Device "gpu"'
          echo 'EndSection'
          echo 'Section "ServerLayout"'
          echo '  Identifier "mlx"'
          echo '  Screen "screen"'
          i=0
          for ev in /dev/input/event*; do
            [ -e "$ev" ] || continue
            echo "  InputDevice \\"in$i\\""
            i=$((i+1))
          done
          echo 'EndSection'
          i=0
          for ev in /dev/input/event*; do
            [ -e "$ev" ] || continue
            echo 'Section "InputDevice"'
            echo "  Identifier \\"in$i\\""
            echo '  Driver "evdev"'
            echo "  Option \\"Device\\" \\"$ev\\""
            echo 'EndSection'
            i=$((i+1))
          done
        } > /etc/X11/xorg.conf.d/10-mlx-input.conf
        cat > /root/.xinitrc <<'XINITRC'
        #!/bin/sh
        xset s off -dpms 2>/dev/null
        /usr/libexec/at-spi-bus-launcher --launch-immediately &
        exec dbus-launch --exit-with-session startxfce4
        XINITRC
        chmod 755 /root/.xinitrc
        echo "mlx-desktop: starting X on :0 ($(ls /dev/input/event* 2>/dev/null | wc -l) input devices)"
        exec xinit /root/.xinitrc -- /usr/bin/Xorg :0 vt1 -keeptty -novtswitch -sharevts -nolisten tcp -noreset

        """
    }

    // MARK: guest commands the host runs (pure)

    /// Start the desktop on a live guest, detached from the exec (same shape
    /// as the shell tool's background wrapper, so the agent channel returns).
    static var startCommand: String {
        "(\(VzGuest.desktopStartGuestPath)) </dev/null >>\(desktopLogPath) 2>&1 &"
    }

    /// Launch the installer detached; `pollCommand` follows it.
    static var launchProvisionCommand: String {
        "chmod 755 \(provisionGuestPath); (\(provisionGuestPath)) </dev/null >>\(installLogPath) 2>&1 &"
    }

    /// The install's last log bytes plus the done marker once it finished.
    static var pollCommand: String {
        "tail -c 1500 \(installLogPath) 2>/dev/null; [ -f \(doneFilePath) ] && echo \(doneMarker)$(cat \(doneFilePath))"
    }

    /// Prints the marker's content ("provisioned=N") or nothing.
    static var checkProvisionedCommand: String { "cat \(markerPath) 2>/dev/null; true" }

    static func isProvisioned(checkOutput: String) -> Bool {
        checkOutput.contains("provisioned=\(provisionVersion)")
    }

    enum PollOutcome: Equatable {
        /// Still running; the payload is the last non-empty log line.
        case installing(String)
        case done(exitCode: Int32)
    }

    static func pollOutcome(pollOutput: String) -> PollOutcome {
        if let range = pollOutput.range(of: doneMarker, options: .backwards) {
            let digits = pollOutput[range.upperBound...].prefix { $0.isNumber }
            return .done(exitCode: Int32(digits) ?? -1)
        }
        let last = pollOutput.split(separator: "\n").last(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty })
        return .installing(last.map(String.init) ?? "")
    }

    /// Why the install cannot start (nil = go ahead). The kernel refusal wins
    /// since it names the fix; then apt needs a network.
    static func installRefusal(networkEnabled: Bool, kernelRefusal: String?) -> String? {
        if let kernelRefusal { return kernelRefusal }
        if !networkEnabled {
            return "the desktop install needs sandbox networking (Settings > Agent Sandbox > Network) for apt-get"
        }
        return nil
    }

    /// The Settings transition. On implies the sandbox and its network (the
    /// desktop IS the guest, and apt installs it); off leaves both as they are.
    static func withDesktop(_ on: Bool, _ config: ServerOptions.SandboxConfig) -> ServerOptions.SandboxConfig {
        var c = config
        c.desktop = on
        if on { c.enabled = true; c.network = true }
        return c
    }

    /// One line for the agent prompt when the tool is allowed and the desktop
    /// is up. Names the size so a model reasons about coordinates correctly.
    static var promptLine: String {
        "A Linux XFCE desktop (\(display.width)x\(display.height), X11, Firefox installed) is available through the `computer` tool: observe first, act on element ids, screenshot only when the tree lacks what you need. "
        + "When the user says to use the computer or the desktop, use `computer`, not browse/webSearch. "
        + "Web research: ONE computer research call with the query and the number of sites the user asked for (up to 40) visits them all and returns a digest; then summarize it. For a single page: navigate, then read. Never invent URLs. "
        + "Apps: install with shell `apt-get install -y <package>` (doom: chocolate-doom freedoom, then open doom; spreadsheet: libreoffice-calc libreoffice-gtk3, then open libreoffice --calc), then computer open <command>, then observe/type/key to work in it. In a spreadsheet type into the focused cell and move with Tab (next column) and Return (next row)."
    }
}
