import { N } from "../i18n/i18n";
// Prompt examples from MLX Serve H3PromptExamples.swift (MIT).
const videoPrompts = {
  ltx: [
    {
      title: N("Talking character (dialogue)"),
      body: 'Medium close-up of a woman in her thirties with short auburn hair, seated at a kitchen table in warm morning light. She looks into the camera and says warmly, "Good morning. I made coffee — it\'s still hot." She pauses, glancing toward the window, then adds with a small smile, "Come sit with me for a minute." Her voice is clear and natural, speaking English. Soft room tone with a faint clink of a cup. The camera holds steady at eye level.',
    },
    {
      title: N("Cinematic character"),
      body: "Medium shot of a young woman with dark curly hair and freckles, wearing a beige wool coat, walking slowly down a rain-slicked cobblestone street at dusk. She holds a folded paper map in one hand and glances up at the glowing shop windows. The camera tracks her from the side at eye level, then slowly dollies in as she stops. Warm amber light spills from the windows onto the wet stones, contrasting with the deep blue-grey sky. Light rain falls continuously, catching the light.",
    },
    {
      title: N("Nature aerial"),
      body: "A wide aerial shot sweeps low over a pine forest at sunrise, mist clinging to the treetops in thick white ribbons. The camera glides forward steadily, revealing a narrow river cutting through the valley below, its surface catching the gold of the early sun. A flock of birds lifts off in a loose spiral. Lighting is soft, warm, and directional from the right. Colors are saturated emerald greens and amber golds.",
    },
    {
      title: N("Product close-up"),
      body: "Close-up of hands in a sunlit kitchen kneading bread dough on a floured wooden counter. The camera holds steady at a low angle, focused tight on the rhythmic press-and-fold motion. Flour dust rises and catches in the shaft of morning light from a window on the left. The hands belong to an older man in a rolled blue shirt, skin weathered and dusted white. Warm natural backlight, muted earth tones.",
    },
  ],
  h3Base: [
    {
      title: N("Character speaking (dialogue)"),
      body: "integrated_multimodal_description:\n[Shot 1] Cinematic, medium close-up, static shot. An on-screen woman in her early thirties (S1) sits in the center of the frame at a rustic wooden kitchen table. She has warm brown eyes, loose wavy brunette hair tied in a messy bun, and wears an oversized, cream-colored chunky knit sweater. The modern farmhouse kitchen behind her features white subway tile, a silver espresso machine, and a hanging pothos plant softly blurred in the background. Bright, warm morning sunlight pours in from an off-frame window to the left, casting a soft, golden glow across the side of her face and illuminating the steam rising from a white ceramic mug resting on the table. Looking directly into the camera lens with a relaxed, welcoming smile, the woman (S1) leans forward slightly, gently resting her forearms on the table, and says in a warm, conversational tone, <d>[English] Good morning. I made coffee. Come sit with me.</d> As she finishes speaking, she tilts her head slightly and maintains her gaze, her shoulders visibly relaxing.\n\noverall_soundscape:\nFaint, continuous ambient chirping of birds sets a morning tone, accompanied by the distinct rustle of heavy knit fabric as the woman shifts forward. A subtle, dull thud is heard as her forearms rest against the wooden table, followed by her clear, foreground spoken dialogue.\n\nnon_diegetic_music:\nSolo acoustic guitar, slow tempo, playing a sparse and repetitive fingerpicking pattern with soft dynamics that sits quietly beneath the dialogue.",
    },
    {
      title: N("Scene with its own soundtrack"),
      body: "integrated_multimodal_description:\n[Shot 1] Cinematic, low aerial wide shot, the camera continuously moving forward while it pedestals up and rolls gently clockwise over a rugged, dark volcanic coastline. Warm, low-angle golden hour sunlight streams in from the left, casting long shadows and highlighting the jagged textures of parallel black basalt ribs that stretch from the bottom foreground out into the vast, deep blue-green ocean. Heavy, rhythmic ocean swells roll in from the background, colliding violently with the solid rock formations. The continuous impact sends explosive bursts of bright white surf and fine, golden-lit mist high into the air. As the camera steadily climbs and banks, the turbulent white water churns vigorously, spilling back over the dark, grooved stones into the sea, revealing a wider expanse of the jagged shoreline fading into the horizon under the vibrant sunset light.\n\noverall_soundscape:\nA pronounced, continuous roar of heavy wind rushing past the microphone, layered over the deep, booming thuds of massive ocean swells crashing against solid rock, followed immediately by the loud, hissing splash of churning surf and water continuously cascading back into the sea.\n\nnon_diegetic_music:\nN/A",
    },
    {
      title: N("Close-up with texture and sound"),
      body: "integrated_multimodal_description:\n[Shot 1] Cinematic, close-up shot with a slow push in, framing a thick, worn oak wooden counter generously dusted with fine white flour. An older man's weathered, wrinkled hands, emerging from faded blue rolled-up linen sleeves, dominate the center of the frame. The hands rhythmically press into a smooth, elastic ball of bread dough with the heels of the palms, folding the soft mass over itself and giving it a quarter turn with steady, practiced precision. Strong, warm morning sunlight streams in diagonally from the upper left, casting deep, textured shadows and intensely backlighting the scene. The directional light catches vibrant, powdery clouds of flour dust that float and swirl gracefully in the air above the counter. With each firm push of the dough, a small puff of dry flour scatters across the wooden surface, and the elastic dough slightly springs back as the hands momentarily release their pressure, while the softly blurred background implies the rustic warmth of a traditional kitchen.\n\noverall_soundscape:\nRhythmic, heavy thuds of the dough impacting the solid wooden board dominate the foreground, accompanied by the dry, powdery friction of skin sliding over scattered flour. A faint, slightly sticky stretching sound is clearly heard each time the dough is folded back on itself, layered over a quiet, airy room tone.\n\nnon_diegetic_music:\nSolo acoustic guitar, slow tempo, featuring warm, steady fingerpicking that gently underscores the steady rhythm of the kneading.",
    },
    {
      title: N("From an attached first frame"),
      body: "For the target video, at 0.00 seconds into the target video, <Picture 1> (from [Shot 1]) is fully referenced.\n\nintegrated_multimodal_description:\n[Shot 1] Cinematic, medium shot with a slow push in, opening on the exact composition, subjects and lighting of <Picture 1> and holding their appearance throughout. The subject begins to move within the frame while the light direction, colour palette and background stay continuous with the reference image. The camera pushes in with small amplitude at slow speed, closing the distance without cutting, so the framing tightens gradually around the subject as the action develops. Small physical details continue moving throughout: fabric settles, hair shifts, and the light on the subject's face changes slightly as the distance closes. The shot holds its final framing for the last moment without a cut.\n\noverall_soundscape:\nA quiet, continuous room tone matching the location, with the close, dry sounds of the subject's own movement in the foreground: fabric brushing, a soft footfall, and the faint rustle of clothing as the pose changes.\n\nnon_diegetic_music:\nN/A",
    },
  ],
  h3Reference: [
    {
      title: N("Keep a subject (image reference)"),
      body: "subject_definitions:\n<Subject 1> is the young woman in <Picture 1>, with long dark hair, a blue cardigan and a thin silver necklace.\n\nsummary:\n[reference generation] The target video is a single shot of <Subject 1> reading at a cafe window as afternoon light moves across the table.\n\nretention_analysis:\n<Subject 1> (appears in [Shot 1]): fully_preserved - her face, long dark hair, blue cardigan and silver necklace are retained.\n\ndetailed_description:\nThe target video is in a realistic cinematic style with warm afternoon window light.\n[Shot 1] A medium shot with a slow push in frames <Subject 1> seated beside a cafe window at a small marble table, an open paperback held in both hands. Warm directional light enters from the left through the glass and falls across the table, the rim of a white cup and the side of her face, leaving the room behind her in soft shadow. The thin silver necklace catches the light each time she shifts her weight. She turns a page with her right hand, then glances up toward the street where blurred figures pass outside the glass. Steam rises steadily from the cup beside her and drifts through the shaft of light. She settles back into the chair, rests one forearm on the marble and returns to the page. The camera pushes in with small amplitude at slow speed, tightening from her shoulders to her face and hands while the background compresses behind her. Toward the end of the shot the light shifts perceptibly warmer as cloud clears outside, deepening the contrast on the knit of the cardigan.\n\noverall_soundscape:\nQuiet cafe room tone with the dry rustle of a turning page close to the camera, distant cutlery against ceramic, the low hiss and clunk of an espresso machine further back, and muffled street traffic through the glass.\n\nnon_diegetic_music:\nN/A",
    },
    {
      title: N("Follow a clip's look and pacing (video reference)"),
      body: "subject_definitions:\n<Subject 1> is the coastal landscape in <Video 1>, with dark ridged rock running seaward, white surf along its edges and deep blue-green water beyond.\n<Video 1> is the reference for the target video's camera movement and pacing, a continuous aerial pass with no cuts.\n\nsummary:\n[reference generation] The target video is a low aerial shot moving forward over <Subject 1> at golden hour, following the continuous unbroken camera movement of <Video 1>.\n\nretention_analysis:\n<Subject 1> (appears in [Shot 1]): fully_preserved - the dark ridged rock, the white surf line along its edges, the deep blue-green water and the low warm light are retained.\n<Video 1> (camera movement and pacing structure): weak_reference - only the continuous single-take aerial pacing is followed; the target video is not an edit of it.\n\ndetailed_description:\nThe target video is in a realistic aerial cinematography style with warm low-angle golden-hour light.\n[Shot 1] A low aerial tracking shot glides forward over <Subject 1>, whose parallel ridges run seaward into deep blue-green water. Warm directional sunlight enters from the upper left and rakes across the wet rock, picking out the wide flat tops of the ridges and throwing long shadows into the channels between them. White surf breaks along each edge in sequence, foaming through the gaps and draining back in bright threads as the next set arrives. The camera pedestals up steadily and rolls a few degrees counterclockwise at slow speed, opening the frame onto more open water while the ridges continue past the lower edge. Swell moves through the channels in a slow rhythm and spray lifts briefly where a larger set collides with the outermost rock, catching the light as fine golden mist that drifts inland before falling back. Between sets the water drains off the flat tops in thin bright sheets, leaving the rock dark and wet where the light no longer catches it. The low warm light holds through the end of the shot without a cut.\n\noverall_soundscape:\nA continuous roar of wind across the microphone over the deep booming impact of heavy swell against solid rock, each impact followed by the loud hiss of churning surf draining back through the channels, with distant gulls high above.\n\nnon_diegetic_music:\nN/A",
    },
    {
      title: N("Reuse a soundtrack (audio reference)"),
      body: "subject_definitions:\n<Audio 1> is the ambience reference for the target video, containing rain on glass, distant traffic and a low interior room tone.\n\nsummary:\n[audio reference] The target video is a single interior shot of a rain-streaked window at night, with its ambience following <Audio 1>.\n\nretention_analysis:\n<Audio 1>: reference - the target video's ambience follows the rain density, traffic distance and room tone of <Audio 1> without copying the original signal.\n\ndetailed_description:\nThe target video is in a realistic cinematic style with low-key interior light.\n[Shot 1] A medium static shot holds on a rain-streaked window at night, the room dark except for a warm lamp out of frame to the right that catches the sill and one edge of the glass. Streetlights outside break into soft coloured circles through the water, amber nearest the camera and cold white further off. Individual drops gather at the top of the pane, hold, then run down in irregular lines that swallow smaller drops as they go, leaving bright trails that slowly refill. A car passes below and its headlights sweep across the glass, briefly resolving the pattern of water into sharp points before the room returns to its darker state. Behind the glass the room stays almost black, with only the lamp's warm edge picking out the sill and a single reflected highlight that shifts as the water moves. The camera then pushes in with small amplitude at slow speed until the reflections fill the frame and the window frame itself falls outside it, the coloured circles growing and softening as focus settles on the nearest running drops, holding on the moving water through the end of the shot.\n\noverall_soundscape:\nSteady rain against glass in the near foreground with an irregular tap as heavier drops strike the sill, a low continuous interior room tone beneath it, and the muffled wet hiss of passing traffic rising and falling in the distance, following the texture and density of <Audio 1>.\n\nnon_diegetic_music:\nN/A",
    },
    {
      title: N("Subject + clip + audio (all three)"),
      body: "subject_definitions:\n<Subject 1> is the young man in <Picture 1>, with short wavy brown hair, a dark-grey hooded jacket and a canvas bag over one shoulder.\n<Video 1> is the reference for the target video's camera movement and pacing, a handheld tracking shot that follows its subject from the side.\n<Audio 1> is the ambience reference for the target video, containing wet street traffic, footsteps and light rain.\n\nsummary:\n[reference generation + audio reuse] The target video follows <Subject 1> walking along a rain-slicked street at dusk, using the handheld side-tracking movement of <Video 1> and reusing the ambience of <Audio 1>.\n\nretention_analysis:\n<Subject 1> (appears in [Shot 1]): fully_preserved - his face, short wavy brown hair, dark-grey hooded jacket and canvas bag are retained.\n<Video 1> (camera movement and pacing structure): weak_reference - only the handheld side-tracking movement and its unhurried pacing are followed; the target video is not an edit of it.\n<Audio 1>: partially_copy - the wet-street traffic and rain ambience is copied as the target video's ambience bed, with the subject's own footsteps added.\n\ndetailed_description:\nThe target video is in a realistic cinematic style with cool dusk light and warm shop windows.\n[Shot 1] A handheld tracking shot follows <Subject 1> from the side at eye level as he walks along a rain-slicked pavement at dusk, hands pushed into his pockets and the canvas bag swinging slightly against his hip. Warm amber light spills from shop windows onto the wet stones and pools in the standing water, contrasting with the deep blue-grey of the sky above the rooftops. Fine rain falls continuously, visible where it crosses the lit windows. He glances toward the glass without slowing, his breath faintly visible in the cold. The camera keeps pace beside him with small amplitude, the frame drifting a few degrees as the operator walks, then falls back slightly as he passes a lit doorway so that the warm interior light crosses his face and shoulders. A cyclist passes behind him in the opposite direction. The shot holds on him walking away into the deeper part of the street as the shop lights fall behind.\n\noverall_soundscape:\nThe copied ambience layer from <Audio 1> - the wet hiss of tyres on soaked asphalt and light rain across the whole frame - continues throughout, with his own footfalls landing close to the camera in shallow water and the soft creak of the canvas strap against his jacket.\n\nnon_diegetic_music:\nN/A",
    },
  ],
};

export { videoPrompts };
