// Per-core KDA prefill recurrence: generated by oMLX's `_percore_source(12, ...)` in
// omlx/patches/glm53_kda_recurrence.py of oMLX 0.7.0 (Apache-2.0, see NOTICE), with `MR`
// (value rows per threadgroup) moved to a template argument.

    constexpr int TB = 12;
    constexpr int NT = MR * 8;
    constexpr int TOTAL = H * Dv;
    const int tid = thread_position_in_threadgroup.x;
    const int tg = threadgroup_position_in_grid.x;
    const int b = threadgroup_position_in_grid.z;
    // even-aligned row range [r0, r1) of the flattened (head, value row) axis
    const int r0 = 2 * ((tg * (TOTAL / 2)) / NTG);
    const int r1 = 2 * (((tg + 1) * (TOTAL / 2)) / NTG);
    const int nrows = r1 - r0;
    const int hA = r0 / Dv;
    const int nh = (r1 - 1) / Dv - hA + 1;  // heads covered: 1 or 2
    const int rg = tid / 8;  // value row within the range
    const int ln = tid % 8;  // 16-channel segment
    const int d0 = ln * 16;
    const bool active = r0 + rg < r1;
    const int slot = active ? ((r0 + rg) / Dv - hA) : 0;
    const bool qb2 = (ln & 4) != 0, qb1 = (ln & 2) != 0;
    const int ysel = (qb2 ? 2 : 0) + (qb1 ? 1 : 0);

    threadgroup InT k_s[2][TB][Dk + 8];
    threadgroup InT q_s[2][TB][Dk + 8];
    threadgroup float g_s[2][TB][Dk + 4];
    threadgroup InT v_s[TB][MR];
    threadgroup float b_s[2][TB];

    const size_t qk_row = (size_t)H * Dk;
    const size_t v_row = (size_t)H * Dv;
    const device InT* k_base = k + ((size_t)b * T * H + hA) * Dk;
    const device InT* q_base = q + ((size_t)b * T * H + hA) * Dk;
    const device InT* a_base = a + ((size_t)b * T * H + hA) * Dk;
    const device InT* v_base = v + (size_t)b * T * H * Dv + r0;
    auto beta_base = beta + (size_t)b * T * H + hA;
    device InT* y_row = y + (size_t)b * T * H * Dv + r0 + rg;
    const int hB = min(hA + 1, H - 1);
    const device float* dtb[2] = {dt_bias + (size_t)hA * Dk, dt_bias + (size_t)hB * Dk};
    const float decay[2] = {metal::precise::exp(A_log[hA]), metal::precise::exp(A_log[hB])};
    const float lb = lower_bound[0];

    float4 st[4];
    {
        const device float4* S_in = (const device float4*)(
            state_in + ((size_t)b * H * Dv + (active ? r0 + rg : r0)) * Dk + d0);
        for (int i = 0; i < 4; ++i) st[i] = S_in[i];
    }

    // register prefetch of one block for both head slots
    constexpr int NQK = (2 * TB * (Dk / 4) + NT - 1) / NT;
    constexpr int NV = (TB * (MR / 2) + NT - 1) / NT;
    vec<InT, 4> pk[NQK], pq[NQK], pa[NQK];
    float4 gv[NQK];
    for (int j = 0; j < NQK; ++j) {
        pk[j] = vec<InT, 4>(0);
        pq[j] = vec<InT, 4>(0);
        pa[j] = vec<InT, 4>(0);
    }
    vec<InT, 2> pv[NV];
    InT pb = InT(0);
#define KDA_FETCH(T0N) { \
        const int ttn = min(TB, T - (T0N)); \
        for (int j = 0; j < NQK; ++j) { \
            const int p = tid + j * NT; \
            const int s = p / (TB * (Dk / 4)), rem = p % (TB * (Dk / 4)); \
            const int r = rem / (Dk / 4), c4 = rem % (Dk / 4); \
            if (s < nh && r < ttn) { \
                const size_t off = (size_t)((T0N) + r) * qk_row + (size_t)s * Dk + 4 * c4; \
                pk[j] = *(const device vec<InT, 4>*)(k_base + off); \
                pq[j] = *(const device vec<InT, 4>*)(q_base + off); \
                pa[j] = *(const device vec<InT, 4>*)(a_base + off); \
            } \
        } \
        for (int j = 0; j < NV; ++j) { \
            const int p = tid + j * NT; \
            const int r = p / (nrows / 2), c2 = p % (nrows / 2); \
            if (r < ttn) \
                pv[j] = *(const device vec<InT, 2>*)(v_base + (size_t)((T0N) + r) * v_row + 2 * c2); \
        } \
        if (tid < nh * TB && tid % TB < ttn) \
            pb = beta_base[(size_t)((T0N) + tid % TB) * H + tid / TB]; \
    }
#define KDA_STAGE(TTN) { \
        for (int j = 0; j < NQK; ++j) { \
            const int p = tid + j * NT; \
            const int s = p / (TB * (Dk / 4)), rem = p % (TB * (Dk / 4)); \
            const int r = rem / (Dk / 4), c4 = rem % (Dk / 4); \
            if (s < nh && r < (TTN)) { \
                *(threadgroup vec<InT, 4>*)(&k_s[s][r][4 * c4]) = pk[j]; \
                *(threadgroup vec<InT, 4>*)(&q_s[s][r][4 * c4]) = pq[j]; \
                *(threadgroup float4*)(&g_s[s][r][4 * c4]) = gv[j]; \
            } \
        } \
        for (int j = 0; j < NV; ++j) { \
            const int p = tid + j * NT; \
            const int r = p / (nrows / 2), c2 = p % (nrows / 2); \
            if (r < (TTN)) *(threadgroup vec<InT, 2>*)(&v_s[r][2 * c2]) = pv[j]; \
        } \
        if (tid < nh * TB && tid % TB < (TTN)) b_s[tid / TB][tid % TB] = static_cast<float>(pb); \
    }

    KDA_FETCH(0)

        for (int j = 0; j < NQK; ++j) {
            const int p = tid + j * NT;
            const int s = min(p / (TB * (Dk / 4)), 1);
            const int c4 = (p % (TB * (Dk / 4))) % (Dk / 4);
            for (int c = 0; c < 4; ++c) {
                const float x = decay[s] * (static_cast<float>(pa[j][c]) + dtb[s][4 * c4 + c]);
                const float e = 1 / (1 + metal::exp(metal::abs(x)));
                const float sig = (x < 0) ? e : 1 - e;
                gv[j][c] = metal::precise::exp(lb * sig);
            }
        }
    KDA_STAGE(min(TB, T))
    threadgroup_barrier(mem_flags::mem_threadgroup);

    float yq0 = 0.0f, yq1 = 0.0f, yq2 = 0.0f, yq3 = 0.0f;
    for (int t0 = 0; t0 < T; t0 += TB) {
        const int tt = min(TB, T - t0);
        const bool more = t0 + TB < T;
        if (more) KDA_FETCH(t0 + TB)
        if (active) {
            if (tt == TB) {

        { // step 0
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][0][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][0][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][0][d0];
            const float bt = b_s[slot][0];
            const float vt = static_cast<float>(v_s[0][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq0 = o;
        }

        { // step 1
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][1][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][1][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][1][d0];
            const float bt = b_s[slot][1];
            const float vt = static_cast<float>(v_s[1][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq1 = o;
        }

        { // step 2
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][2][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][2][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][2][d0];
            const float bt = b_s[slot][2];
            const float vt = static_cast<float>(v_s[2][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq2 = o;
        }

        { // step 3
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][3][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][3][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][3][d0];
            const float bt = b_s[slot][3];
            const float vt = static_cast<float>(v_s[3][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq3 = o;
        }

        { // step 4
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][4][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][4][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][4][d0];
            const float bt = b_s[slot][4];
            const float vt = static_cast<float>(v_s[4][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            {
                const float ya = (qb2 ? yq2 : yq0) + simd_shuffle_xor(qb2 ? yq0 : yq2, 4);
                const float yb = (qb2 ? yq3 : yq1) + simd_shuffle_xor(qb2 ? yq1 : yq3, 4);
                float yv = (qb1 ? yb : ya) + simd_shuffle_xor(qb1 ? ya : yb, 2);
                yv += simd_shuffle_xor(yv, 1);
                if ((ln & 1) == 0 && active)
                    y_row[(size_t)(t0 + 0 + ysel) * v_row] = static_cast<InT>(yv);
            }
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq0 = o;
        }

        { // step 5
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][5][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][5][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][5][d0];
            const float bt = b_s[slot][5];
            const float vt = static_cast<float>(v_s[5][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq1 = o;
        }

        { // step 6
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][6][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][6][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][6][d0];
            const float bt = b_s[slot][6];
            const float vt = static_cast<float>(v_s[6][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq2 = o;
        }

        { // step 7
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][7][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][7][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][7][d0];
            const float bt = b_s[slot][7];
            const float vt = static_cast<float>(v_s[7][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq3 = o;
        }

        { // step 8
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][8][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][8][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][8][d0];
            const float bt = b_s[slot][8];
            const float vt = static_cast<float>(v_s[8][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            {
                const float ya = (qb2 ? yq2 : yq0) + simd_shuffle_xor(qb2 ? yq0 : yq2, 4);
                const float yb = (qb2 ? yq3 : yq1) + simd_shuffle_xor(qb2 ? yq1 : yq3, 4);
                float yv = (qb1 ? yb : ya) + simd_shuffle_xor(qb1 ? ya : yb, 2);
                yv += simd_shuffle_xor(yv, 1);
                if ((ln & 1) == 0 && active)
                    y_row[(size_t)(t0 + 4 + ysel) * v_row] = static_cast<InT>(yv);
            }
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq0 = o;
        }

        { // step 9
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][9][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][9][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][9][d0];
            const float bt = b_s[slot][9];
            const float vt = static_cast<float>(v_s[9][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq1 = o;
        }

        { // step 10
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][10][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][10][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][10][d0];
            const float bt = b_s[slot][10];
            const float vt = static_cast<float>(v_s[10][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq2 = o;
        }

        { // step 11
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][11][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][11][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][11][d0];
            const float bt = b_s[slot][11];
            const float vt = static_cast<float>(v_s[11][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            yq3 = o;
        }

            {
                const float ya = (qb2 ? yq2 : yq0) + simd_shuffle_xor(qb2 ? yq0 : yq2, 4);
                const float yb = (qb2 ? yq3 : yq1) + simd_shuffle_xor(qb2 ? yq1 : yq3, 4);
                float yv = (qb1 ? yb : ya) + simd_shuffle_xor(qb1 ? ya : yb, 2);
                yv += simd_shuffle_xor(yv, 1);
                if ((ln & 1) == 0 && active)
                    y_row[(size_t)(t0 + 8 + ysel) * v_row] = static_cast<InT>(yv);
            }
            } else {
for (int t = 0; t < tt; ++t) 
        { // step t
            const threadgroup float4* g4 = (const threadgroup float4*)&g_s[slot][t][d0];
            const threadgroup vec<InT, 4>* k4 = (const threadgroup vec<InT, 4>*)&k_s[slot][t][d0];
            const threadgroup vec<InT, 4>* q4 = (const threadgroup vec<InT, 4>*)&q_s[slot][t][d0];
            const float bt = b_s[slot][t];
            const float vt = static_cast<float>(v_s[t][rg]);
            float4 kf[4];
            for (int i = 0; i < 4; ++i) kf[i] = float4(k4[i]);
            // decay the state row in place, then k.S
            float4 p4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] * g4[i];
                p4 += st[i] * kf[i];
            }
            float p = (p4.x + p4.y) + (p4.z + p4.w);
            p += simd_shuffle_xor(p, 4);
            p += simd_shuffle_xor(p, 2);
            p += simd_shuffle_xor(p, 1);
            // delta rule update, then q.S
            const float delta = (vt - p) * bt;
            float4 o4 = 0.0f;
            for (int i = 0; i < 4; ++i) {
                st[i] = st[i] + kf[i] * delta;
                o4 += st[i] * float4(q4[i]);
            }
            const float o = (o4.x + o4.y) + (o4.z + o4.w);
            {
                float yv = o;
                yv += simd_shuffle_xor(yv, 4);
                yv += simd_shuffle_xor(yv, 2);
                yv += simd_shuffle_xor(yv, 1);
                if (ln == 0 && active) y_row[(size_t)(t0 + t) * v_row] = static_cast<InT>(yv);
            }
        }

            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        if (more) {

        for (int j = 0; j < NQK; ++j) {
            const int p = tid + j * NT;
            const int s = min(p / (TB * (Dk / 4)), 1);
            const int c4 = (p % (TB * (Dk / 4))) % (Dk / 4);
            for (int c = 0; c < 4; ++c) {
                const float x = decay[s] * (static_cast<float>(pa[j][c]) + dtb[s][4 * c4 + c]);
                const float e = 1 / (1 + metal::exp(metal::abs(x)));
                const float sig = (x < 0) ? e : 1 - e;
                gv[j][c] = metal::precise::exp(lb * sig);
            }
        }
            KDA_STAGE(min(TB, T - t0 - TB))
            threadgroup_barrier(mem_flags::mem_threadgroup);
        }
    }
#undef KDA_FETCH
#undef KDA_STAGE

    if (active) {
        device float4* S_out = (device float4*)(
            state_out + ((size_t)b * H * Dv + r0 + rg) * Dk + d0);
        for (int i = 0; i < 4; ++i) S_out[i] = st[i];
    }
